# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f76874f9ed991467b12fe547f06ccee"
name = "App test"
handle = "app-test-488"
application_url = "https://steadily-massive-civet.ngrok-free.app/shopify/auth"
embedded = true

[build]
dev_store_url = "quickstart-28ce93ff.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_write_checkouts,unauthenticated_write_customers"

[auth]
redirect_urls = [
  "https://steadily-massive-civet.ngrok-free.app/shopify/auth/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://steadily-massive-civet.ngrok-free.app/v1/webhooks/customers-redact"
  customer_data_request_url = "https://steadily-massive-civet.ngrok-free.app/v1/webhooks/data-request"
  shop_deletion_url = "https://steadily-massive-civet.ngrok-free.app/v1/webhooks/shop-redact"

[pos]
embedded = false
