# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "69db3caf17c4eb5befc0055e4427fc96"
name = "Sign panel app"
handle = "sign-panel-app"
application_url = "https://spf.watermelon.icu/shopify/auth"
embedded = true

[build]
dev_store_url = "sts-staging.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,unauthenticated_read_checkouts,unauthenticated_read_content,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_metaobjects,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,unauthenticated_read_product_tags,unauthenticated_write_checkouts,unauthenticated_write_customers"

[auth]
redirect_urls = [ "https://spf.watermelon.icu/shopify/auth/callback" ]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://spf.watermelon.icu/v1/webhooks/customers-redact"
  customer_data_request_url = "https://spf.watermelon.icu/v1/webhooks/data-request"
  shop_deletion_url = "https://spf.watermelon.icu/v1/webhooks/shop-redact"

[pos]
embedded = false
