import { create } from 'zustand'
import { CHANEL_COLOUR_OPTIONS, CHANNEL_SIZE_OPTIONS, COLOURS, FIXING_METHOD_OPTIONS, INTERLOCKING_COLOUR_OPTIONS, PANEL_COLOURS, PANEL_MATERIAL_OPTIONS, POST_LENGTH, POST_SIZE_OPTIONS, RADIUS_CORNER_OPTIONS, SHAPE_OPTIONS } from '../constants'

const useStore = create((set) => ({
  selectedOptionTab: -1,
  checkedPostOption: false,
  checkedClipOption: false,
  width: 1000,
  height: 1000,
  size: '450',
  mountHeight: 2000,
  postQuantity: 1,
  channelInfos: {
    channels: [],
    interlockings: []
  },
  cartId: '',
  checkoutUrl: '',
  numOfClips: 0,

  selectedChannelSize: CHANNEL_SIZE_OPTIONS[1],
  selectedChannelColour: CHANEL_COLOUR_OPTIONS[0],
  selectedPanelMaterial: PANEL_MATERIAL_OPTIONS[0],
  selectedPanelColour: PANEL_COLOURS.WHITE_GREY,
  selectedPanelShape: SHAPE_OPTIONS[0],
  selectedRadius: RADIUS_CORNER_OPTIONS[0],
  selectedInterlockingColour: INTERLOCKING_COLOUR_OPTIONS[0],
  selectedFixingMethod: FIXING_METHOD_OPTIONS[0],
  selectedPostSize: POST_SIZE_OPTIONS[0],
  selectedPostColour: COLOURS.GREY,
  selectedPostLength: POST_LENGTH['3M'],
  selectedPostCapColour: COLOURS.GREY,
  selectedPostClipColour: COLOURS.STAINLESS,
  shopifyMap: {},
  variantMapSku: [],
  channelQuantity: 1,
  setChannelQuantity:  (value) => set(() => ({ channelQuantity: value })),
  specificChannelQuantity: false,
  setSpecificChannelQuantity:  (value) => set(() => ({ specificChannelQuantity: value })),
  setSelectedOptionTab: (value) => set(() => ({ selectedOptionTab: value })),
  setCheckedPostOption: (value) => set(() => ({ checkedPostOption: value })),
  setCheckedClipOption: (value) => set(() => ({ checkedClipOption: value })),
  setSize: (value) => set(() => ({ size: value })),
  setWidth: (value) => set(() => ({ width: value })),
  setHeight: (value) => set(() => ({ height: value })),

  setSelectedChannelSize: (value) => set(() => ({ selectedChannelSize: value })),
  setSelectedChannelColour: (value) => set(() => ({ selectedChannelColour: value })),
  setSelectedPanelMaterial: (value) => set(() => ({ selectedPanelMaterial: value })),
  setSelectedPanelColour: (value) => set(() => ({ selectedPanelColour: value })),
  setSelectedPanelShape: (value) => set(() => ({ selectedPanelShape: value })),
  setSelectedRadius: (value) => set(() => ({ selectedRadius: value })),
  setSelectedInterlockingColour: (value) => set(() => ({ selectedInterlockingColour: value })),
  setSelectedFixingMethod: (value) => set(() => ({ selectedFixingMethod: value })),
  setSelectedPostSize: (value) => set(() => ({ selectedPostSize: value })),
  setSelectedPostColour: (value) => set(() => ({ selectedPostColour: value })),
  setMountHeight: (value) => set(() => ({ mountHeight: value })),
  setPostQuantity: (value) => set(() => ({ postQuantity: value })),
  setSelectedPostLength: (value) => set(() => ({ selectedPostLength: value })),
  setSelectedPostCapColour: (value) => set(() => ({ selectedPostCapColour: value })),
  setSelectedPostClipColour: (value) => set(() => ({ selectedPostClipColour: value })),
  setChannelInfos: (value) => set(() => ({ channelInfos: value })),
  setCartId: (value) => set(() => ({ cartId: value })),
  setCheckoutUrl: (value) => set(() => ({ checkoutUrl: value })),
  setNumOfClips: (value) => set(() => ({ numOfClips: value })),
  setShopifyMap: (value) => set(() => ({ shopifyMap: value })),
  setVariantMapSku: (value) => set(() => ({ variantMapSku: value })),
}))

export default useStore